CREATE TABLE "SPORT_USER" (
	"USER_EMAIL"	VARCHAR2(30)  PRIMARY KEY,
	"NICKNAME"	VARCHAR2(30),
	"PASSWORD"	VARCHAR2(30),
	"PHONE_NUMBER"	VARCHAR2(20),
	"GENDER"	VARCHAR2(10),
	"IMAGE"	VARCHAR2(100)
);

CREATE TABLE "FACILITY" (
	"FACILITY_ID"	NUMBER(10)	PRIMARY KEY,
	"FACILITY_NAME"	VARCHAR2(100),
	"ADDRESS"	VARCHAR2(100),
	"PHONE_NUMBER"	VARCHAR2(20),
	"CAPACITY"	NUMBER(10),
	"EVENT"	VARCHAR2(100),
	"IMAGE"	VARCHAR2(100)
);

CREATE TABLE "FACILITY_RESERVE" (
	"FACILITY_ID"	NUMBER(10)	REFERENCES FACILITY (FACILITY_ID),
	"USER_EMAIL"	VARCHAR2(30)	REFERENCES SPORT_USER (USER_EMAIL),
	"START_TIME"	DATE		NULL,
	"END_TIME"	DATE		NULL
);

CREATE TABLE "TEAMS" (
	"TEAM_ID"	NUMBER(10)	PRIMARY KEY,
	"USER_EMAIL"	VARCHAR2(30)  REFERENCES SPORT_USER (USER_EMAIL),
	"GENDER"	VARCHAR2(10),
	"TEAM_NAME"	VARCHAR2(100),
	"IMAGE"	VARCHAR2(100)
);

CREATE TABLE "TEAM_MEMBER" (
	"TEAM_ID"	NUMBER(10)	REFERENCES TEAMS (TEAM_ID),
	"USER_EMAIL"	VARCHAR2(30) REFERENCES SPORT_USER (USER_EMAIL),
	"HIRE_DATE"	DATE 
);

CREATE TABLE "FREE_BBS" (
	"BBS_ID"	NUMBER(10)	PRIMARY KEY,
	"USER_EMAIL"	VARCHAR2(30)	REFERENCES SPORT_USER (USER_EMAIL),
	"SUBJECT"	VARCHAR2(1000),
	"CONTENT"	VARCHAR2(3000),
	"WRITE_DATE"	DATE,
	"IMAGE"	VARCHAR2(100),
);

CREATE TABLE "FREE_COMMENTS" (
	"COMMENT_IDX"	NUMBER(10)	PRIMARY KEY,
	"USER_EMAIL"	VARCHAR2(30)	 REFERENCES SPORT_USER (USER_EMAIL),
	"BBS_ID"	NUMBER(10)		REFERENCES FREE_BBS (BBS_ID),
	"CONTENT"	VARCHAR2(1000),
	"WRITE_DATE"	DATE
);

CREATE TABLE "JOIN_BBS" (
	"BBS_ID"	NUMBER(10)	PRIMARY KEY,
	"USER_EMAIL"	VARCHAR2(30)	REFERENCES SPORT_USER (USER_EMAIL),
	"TEAM_ID"	NUMBER(10)	REFERENCES TEAMS (TEAM_ID),
	"SUBJECT"	VARCHAR2(1000),
	"TIME"	VARCHAR2(1000),
	"MEMBER_MAX"	VARCHAR2(1000),
	"LIMIT"	VARCHAR2(1000),
	"PLACE"	VARCHAR2(1000),
	"EVENT"	VARCHAR2(1000),
	"CONTENT"	VARCHAR2(3000),
	"WRITE_DATE"	DATE,
	"IMAGE"	VARCHAR2(100),
	"TEAM_NAME"	VARCHAR2(100)
);

CREATE TABLE "JOIN_COMMENTS" (
	"COMMENT_IDX"	NUMBER(10)	PRIMARY KEY,
	"BBS_ID"	NUMBER(10)	REFERENCES JOIN_BBS (BBS_ID),
	"USER_EMAIL"	VARCHAR2(30)	REFERENCES SPORT_USER (USER_EMAIL),
	"CONTENT"	VARCHAR2(1000),
	"WRITE_DATE"	DATE
);

INSERT INTO SPORT_USER (USER_EMAIL, NICKNAME, PASSWORD,
                        PHONE_NUMBER, GENDER)
VALUES ('wkdms1213@gmail.com', '9jani', '1111', '010-1111-1111', 'F')
;


INSERT INTO FREE_BBS (BBS_ID, USER_EMAIL, SUBJECT, CONTENT,
                        WRITE_DATE)
VALUES (1, 'wkdms1213@gmail.com', '축구', '축구하실분', SYSDATE)
;

